# Site settings
title: Sarah's Serious Fire Recipes
author: Sarah
description:
  A searchable d20 5e spell list, sorted by class and level.
baseurl: /recipes # the subpath of your site, e.g. /blog/
url: swmitch3.github.io # the base hostname & protocol for your site
source-url: https://github.com/swmitch3/recipes/
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"